//
// Copyright (c) 2016-2017 Eclipse Microprofile Contributors:
// Heiko Braun
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

[[architecture]]
== Architecture

The Eclipse MicroProfile Health Check(MP-HC) specification defines a single container runtime mechanism for validating
the availability and status of a MicroProfile specification. This is primaryly intended as a machine to machine(M2M)
mechanism for use in containerized environments like cloud providers and containerized environments. Example of
existing specifications from those environments include https://docs.cloudfoundry.org/devguide/deploy-apps/healthchecks.html[Cloud Foundry Health Checks] and
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes[Kubernetes Liveness and Rediness Probes].

The MP-HC architecture consists of a single /health endpoint in a MicroProfile runtime that represents the status of
the entire runtime. This /health endpoint is expected to be associated with a configurable context, such as a web
application deploymnet, that can be configured with settings such as port, virtual-host, security, etc.
Futher, the MP-HC defines the notion of a procedure that represents the health of a particular
subcomponent of an application. There can be zero or more procedures in an application, and the
overall health of the application as reflected via the /health endpoint is the logical AND of
all of the procedure health status.

The 1.0 version of the MP-HC specification does not define how the /health endpoint may be partioned in the event
that the MicroProfile runtime supports deployment of multiple JAX-RS applications. If an implementation wishes to
support multiple JAX-RS application within a MicroProfile runtime, the semantics of the /health endpoint are
expected to be the logical AND of all the application in the runtime. The exact details of this are deferred to
a future version of the MP-HC specification.

The <<Healthcheck Specification Protocol 1.0>> section details the full requirements of a MP-HC
implementation with respect to each of these topics.
